apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deep-learning-research-agent.configmapName" . }}
  labels:
    {{- include "deep-learning-research-agent.labels" . | nindent 4 }}
data:
  # Application configuration
  APP_NAME: {{ .Values.app.name | quote }}
  APP_HOST: {{ .Values.app.host | quote }}
  APP_PORT: {{ .Values.app.port | quote }}
  APP_RELOAD: {{ .Values.app.reload | quote }}
  APP_DEBUG: {{ .Values.app.debug | quote }}

  # Server configuration
  SERVER_HOST: {{ .Values.app.host | quote }}
  SERVER_PORT: {{ .Values.app.port | quote }}

  # LangSmith configuration
  LANGSMITH_TRACING: {{ .Values.langsmith.tracing | quote }}
  LANGSMITH_PROJECT: {{ .Values.langsmith.project | quote }}

  # Database configuration (if enabled)
  {{- if .Values.database.enabled }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  {{- end }}

  # Agent limits
  MAX_CONCURRENT_RESEARCH_UNITS: {{ .Values.limits.maxConcurrentResearchUnits | quote }}
  MAX_RESEARCHER_ITERATIONS: {{ .Values.limits.maxResearcherIterations | quote }}

  {{- range .Values.extraEnv }}
  {{- if not .valueFrom }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
  {{- end }}
