apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deep-learning-research-agent.secretName" . }}
  labels:
    {{- include "deep-learning-research-agent.labels" . | nindent 4 }}
type: Opaque
data:
  # LangSmith API key
  {{- if .Values.langsmith.apiKey }}
  LANGSMITH_API_KEY: {{ .Values.langsmith.apiKey | b64enc | quote }}
  {{- end }}

  # Tavily API key for web search
  {{- if .Values.tavily.apiKey }}
  TAVILY_API_KEY: {{ .Values.tavily.apiKey | b64enc | quote }}
  {{- end }}

  # Supervisor model credentials
  {{- if .Values.supervisorModel.apiKey }}
  SUPERVISOR_MODEL_API_KEY: {{ .Values.supervisorModel.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.supervisorModel.baseUrl }}
  SUPERVISOR_MODEL_BASE_URL: {{ .Values.supervisorModel.baseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.supervisorModel.name }}
  SUPERVISOR_MODEL_NAME: {{ .Values.supervisorModel.name | b64enc | quote }}
  {{- end }}
  {{- if .Values.supervisorModel.provider }}
  SUPERVISOR_MODEL_PROVIDER: {{ .Values.supervisorModel.provider | b64enc | quote }}
  {{- end }}

  # Research sub-agent credentials
  {{- if .Values.researcherModel.apiKey }}
  RESEARCHER_MODEL_API_KEY: {{ .Values.researcherModel.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.researcherModel.baseUrl }}
  RESEARCHER_MODEL_BASE_URL: {{ .Values.researcherModel.baseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.researcherModel.name }}
  RESEARCHER_MODEL_NAME: {{ .Values.researcherModel.name | b64enc | quote }}
  {{- end }}
  {{- if .Values.researcherModel.provider }}
  RESEARCHER_MODEL_PROVIDER: {{ .Values.researcherModel.provider | b64enc | quote }}
  {{- end }}

  # Database credentials (if enabled)
  {{- if .Values.database.enabled }}
  {{- if .Values.database.user }}
  POSTGRES_USER: {{ .Values.database.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
  {{- end }}
