import os

# Supervisor model used as main agent overseeing sub-agents
SUPERVISOR_MODEL_API_KEY = os.getenv("SUPERVISOR_MODEL_API_KEY", "")
SUPERVISOR_MODEL_BASE_URL = os.getenv("SUPERVISOR_MODEL_BASE_URL", "")
SUPERVISOR_MODEL_NAME = os.getenv("SUPERVISOR_MODEL_NAME", "")
SUPERVISOR_MODEL_PROVIDER = os.getenv("SUPERVISOR_MODEL_PROVIDER", "")

# Researcher model used for conducting research
RESEARCHER_MODEL_API_KEY = os.getenv("RESEARCHER_MODEL_API_KEY", "")
RESEARCHER_MODEL_BASE_URL = os.getenv("RESEARCHER_MODEL_BASE_URL", "")
RESEARCHER_MODEL_NAME = os.getenv("RESEARCHER_MODEL_NAME", "")
RESEARCHER_MODEL_PROVIDER = os.getenv("RESEARCHER_MODEL_PROVIDER", "")

# Limits on resource usage
MAX_CONCURRENT_RESEARCH_UNITS = os.getenv("MAX_CONCURRENT_RESEARCH_UNITS", 3)
MAX_RESEARCHER_ITERATIONS = os.getenv("MAX_RESEARCHER_ITERATIONS", 3)