name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: deep-learning-research-agent
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}

      - name: Extract short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update values.yaml with new image tag
        run: |
          sed -i 's/tag: ".*"/tag: "${{ steps.sha.outputs.short_sha }}"/' helm/values.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: update image tag to ${{ steps.sha.outputs.short_sha }}"
          title: "Update image tag to ${{ steps.sha.outputs.short_sha }} for deployment"
          body: |
            🤖 **Automated Image Tag Update**

            This PR updates the Helm values.yaml file with the latest image tag.

            **Changes:**
            - Updated `image.tag` to `${{ steps.sha.outputs.short_sha }}`
            - Image built from commit: ${{ github.sha }}

            **Docker Image:**
            `${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.short_sha }}`

            This PR was automatically created after successfully building and pushing the Docker image.
          branch: update-image-tag-${{ steps.sha.outputs.short_sha }}
          delete-branch: true
