name: Build and Push Docker Image

on:
  push:
    branches:
      - main

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: deep-learning-research-agent
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # NOTE: Update this sentence if the automated PR body changes.
    if: ${{ !contains(github.event.head_commit.message, 'This PR updates the Helm values.yaml file with the latest image tag.') }}
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}

      - name: Extract short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Update values.yaml with new image tag
        run: |
          sed -i 's/tag: ".*"/tag: "${{ steps.sha.outputs.short_sha }}"/' helm/values.yaml

      - name: Configure git for GPG signing
        run: |
          git config --global user.name "Nathan Thomas"
          git config --global user.email "nwthomas@me.com"
          git config --global commit.gpgsign true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: update image tag to ${{ steps.sha.outputs.short_sha }}"
          title: "Update image tag to ${{ steps.sha.outputs.short_sha }} for deployment"
          # NOTE: Update the if condition for running this entire workflow if the automated PR body changes.
          body: |
            🤖 **Automated Image Tag Update**

            This PR updates the Helm values.yaml file with the latest image tag.

            **Changes:**
            - Updated `image.tag` to `${{ steps.sha.outputs.short_sha }}`
            - Image built from commit: ${{ github.sha }}

            **Docker Image:**
            `${{ env.REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.short_sha }}`

            This PR was automatically created after successfully building and pushing the Docker image.
          branch: update-image-tag
          signoff: true
          committer: Nathan Thomas <nwthomas@me.com>
          author: Nathan Thomas <nwthomas@me.com>
